version: '3.1'

name: "portfavor-api"

services:

  database:
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-portfavor}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-root}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/mysql:rw

  api:
    image: portfavor/api
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      SPRING_PROFILE: "prod"
      DATABASE_HOST: "database"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "${DATABASE_NAME:-portfavor}"
      DATABASE_USERNAME: "${DATABASE_USERNAME:-postgres}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-root}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-root}"
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

volumes:
  db-store:
